{{- if not .Values.redis.password }}
{{- fail "Error: redis.password must be set with --set redis.password=VALUE" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  redis.conf: {{ printf "%s" .Values.redis.password | b64enc | quote }}
