# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
  namespace: default
  labels:
    app: file-server
spec:
  selector:
    matchLabels:
      app: file-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: file-server
      labels:
        app: file-server
    spec:
      containers:
        - name: file-server
          image: ghcr.io/covelo12/journal:master-67bc254
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
