# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: file-server
  namespace: default
spec:
  selector:
    app: file-server
  type: ClusterIP
  ports:
    - name: file-server
      port: 8080
---

