# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: file-server
spec:
  selector:
    matchLabels:
      app: file-server
  replicas: {{ .Values.fileserver.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: file-server
    spec:
      containers:
        - name: file-server
          image: "{{ .Values.fileserver.image.repository}}:{{.Values.fileserver.image.tag }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
