name: Docker Image CI

on:
  push:
    paths:
    -  "fileserver/fileserver.py"
    - "fileserver/Dockerfile"

  workflow_dispatch: # This adds the manual trigger with no inputs   

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout code
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: get_sha
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # Use the GITHUB_ACTOR (your username) as the username
          username: ${{ github.actor }}
          # Use the built-in GITHUB_TOKEN for authentication
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with SHA tag to GHCR
        id: docker_build
        run: |
          # GHCR repository name format: ghcr.io/<OWNER>/<REPOSITORY_NAME>
          # github.repository gives you <OWNER>/<REPOSITORY_NAME> (e.g., 'your-org/your-repo')
          REPO_FULL_PATH="ghcr.io/${{ github.repository }}"
          BRANCH_NAME="${{ github.ref_name }}"
          SHORT_SHA="${{ steps.get_sha.outputs.SHORT_SHA }}"

          # Sanitize branch name for Docker tag (replace slashes with dashes)
          SANITIZED_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '-')

          # Base tag combining branch name and short SHA
          VERSION_TAG="${SANITIZED_BRANCH_NAME}-${SHORT_SHA}"

          echo "Building image: ${REPO_FULL_PATH}:${VERSION_TAG}"

          docker build ./fileserver --tag "${REPO_FULL_PATH}:${VERSION_TAG}"
          docker push "${REPO_FULL_PATH}:${VERSION_TAG}"

          echo "Pushed image: ${REPO_FULL_PATH}:${VERSION_TAG}"

      - name: Tag and push 'latest' for main branch to GHCR
        if: github.ref == 'refs/heads/main' # Only runs if the push was to the 'main' branch
        run: |
          REPO_FULL_PATH="ghcr.io/${{ github.repository }}"
          SHORT_SHA="${{ steps.get_sha.outputs.SHORT_SHA }}"

          # Tag the image that was just built (which has the SHA tag) with 'latest'
          docker tag "${REPO_FULL_PATH}:main-${SHORT_SHA}" "${REPO_FULL_PATH}:latest"
          docker push "${REPO_FULL_PATH}:latest"

          echo "Pushed image: ${REPO_FULL_PATH}:latest"
